const PROPERTIES = [
    {
        "area": "Sunnyvale",
        "manager": "WSB Properties",
        "type": "Studio",
        "rent": 1895,
        "latitude": 37.401010,
        "longitude": -122.016210,
        "address": "624 Morse Ave",
        "notes": "Good reviews. Inconvenient commute. Dogs allowed.",  
    },
    {
        "area": "Sunnyvale",
        "manager": "WSB Properties",
        "type": "1BR",
        "rent": 2000,
        "latitude": 37.385380,
        "longitude": -122.019860,
        "address": "524 E Maude Ave",
        "notes": "Good reviews. Inconvenient commute. Dogs allowed.",
    },
    {
        "area": "San Mateo",
        "manager": "Culligan",
        "type": "Studio, 1BR",
        "rent": 2100,
        "latitude": 37.547990,
        "longitude": -122.310820,
        "address": "49 West 36th Avenue",
        "notes": "Close to Caltrain. Availability Unknown",
    },
    {
        "area": "San Mateo",
        "manager": "Culligan",
        "type": "Studio",
        "rent": 1650,
        "latitude": 37.534220,
        "longitude": -122.296260,
        "address": "3633 Colegrove Street",
        "notes": "Close to Caltrain. Availability Unknown",
    },
    {
        "area": "Mountain View",
        "manager": "Vrent",
        "type": "Studio",
        "rent": 2045,
        "latitude": 37.409410,
        "longitude": -122.111980,
        "address": "2700 Del Medio Ct",
        "notes": "Convenient location. Poor management reviews."
    },
]
